Improvement for remote host mongoimport.
Currently, the utility does support connecting and importing data
(json/csv) to local (in-memory) mongo instance (using mongoimport binary
internally), however, if we try to use the utility connect to a remote
instance and import content there, we are unfortunately not able to do
so.
Reason :
while creating importconfig as -

  mongoImportConfig = new MongoImportConfigBuilder()
      .version(Version.Main.DEVELOPMENT)
      .net(new Net(bind_ip, port, Network.localhostIsIPv6()))
      ....
      .build();
the bind_ip is not recognised by mongoimport binary and the process
terminates complaining :

[mongoimport error]Error parsing command line: unknown option bind_ip
[mongoimport error] try
'/var/folders/bh/vrwtkqdn1nj7jh_0ppky9_p40000gn/T/extract-47a4c341-b11e-40be-92c5-9ab71a97e649mongoimport
--help' for more information
[mongoimport error] 
Feb 04, 2015 10:42:40 AM
de.flapdoodle.embed.process.runtime.AbstractProcess 
SEVERE: failed to call onAfterProcessStart()
java.io.IOException: Could not start process:

We have developed a simple solution and with extending your
de.flapdoodle.embed.mongo.config.Net class and
de.flapdoodle.embed.mongo.runtime.AbstractMongo to facilitate the same.

we would like to get a pull request for this, so that we can contribute
changes from our side.